services:
  cs2-server:
    image: joedwards32/cs2
    container_name: cs2
    environment:
      # Server
      SRCDS_TOKEN: "$SRCDS_TOKEN"
      DEBUG: 0
      STEAMAPPVALIDATE: 0
      CS2_SERVERNAME: "Remi's Nuclear Nutsack"
      CS2_CHEATS: 0
      CS2_PORT: 27015
      CS2_SERVER_HIBERNATE: 0
      CS2_RCON_PORT: 27015
      CS2_LAN: 1
      CS2_RCONPW: "remis"
      CS2_PW: "remis"
      CS2_MAXPLAYERS: 10
      CS2_ADDITIONAL_ARGS: ""
      CS2_CFG_URL: "https://raw.githubusercontent.com/Reggles44/cs2-surf-server/refs/heads/main/cs2.cfg.tgz"

      # Game modes
      CS2_GAMEALIAS: "custom"
      # CS2_GAMETYPE: 3
      # cs2_gamemode: 0
      # CS2_MAPGROUP: mg_active
      # CS2_STARTMAP: de_inferno

      # Workshops
      CS2_HOST_WORKSHOP_COLLECTION: "3711124132"
      CS2_HOST_WORKSHOP_MAP: "surf_utopia_njv"

      # Bots
      CS2_BOT_DIFFICULTY: ""
      CS2_BOT_QUOTA: "0"
      CS2_BOT_QUOTA_MODE: ""

      # TV
      TV_AUTORECORD: 0
      TV_ENABLE: 0
      TV_PORT: 27020
      TV_PW: remis
      TV_RELAY_PW: remis
      TV_MAXRATE: 0
      TV_DELAY: 0

      # Logs
      CS2_LOG: on
      CS2_LOG_MONEY: 0
      CS2_LOG_DETAIL: 0
      CS2_LOG_ITEMS: 0

    volumes:
      - cs2:/home/steam/cs2-dedicated

    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
    stdin_open: true
    tty: true

volumes:
  cs2:
