services:
  cs2-server:
    image: ghcr.io/kus/cs2-modded-server
    container_name: cs2
    environment:
      STEAM_ACCOUNT: "$SRCDS_TOKEN"
      API_KEY: "$SRCDS_TOKEN"
      RCON_PASSWORD: "$RCON_PASSWORD"
      SERVER_PASSWORD: "$SERVER_PASSWORD"

      PORT: 27015
      TICKRATE: 128
      MAXPLAYERS: 8

    volumes:
      - cs2:/home/steam/cs2-dedicated

    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
    stdin_open: true
    tty: true

volumes:
  cs2:

